-- Telegram Premium purchased with the local Stars ledger.
--
-- The plan version and all monetary/duration fields are copied into each
-- payment intent. Checkout therefore never trusts a price supplied by a
-- client and never changes an already issued form after a catalog edit.

ALTER TABLE public.users
    ADD COLUMN premium_updated_at timestamp with time zone;

ALTER TABLE public.account_settings
    ADD COLUMN disallow_unlimited_stargifts boolean DEFAULT false NOT NULL,
    ADD COLUMN disallow_limited_stargifts boolean DEFAULT false NOT NULL,
    ADD COLUMN disallow_unique_stargifts boolean DEFAULT false NOT NULL,
    ADD COLUMN disallow_premium_gifts boolean DEFAULT false NOT NULL,
    ADD COLUMN disallow_stargifts_from_channels boolean DEFAULT false NOT NULL;

CREATE TABLE public.premium_plans (
    months integer NOT NULL,
    duration_days integer NOT NULL,
    amount_stars bigint NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    label text NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT premium_plans_pkey PRIMARY KEY (months),
    CONSTRAINT premium_plans_months_valid CHECK (months > 0 AND months <= 120),
    CONSTRAINT premium_plans_duration_valid CHECK (duration_days > 0 AND duration_days <= 36500),
    CONSTRAINT premium_plans_amount_valid CHECK (amount_stars > 0 AND amount_stars <= 1000000000000000),
    CONSTRAINT premium_plans_version_positive CHECK (version > 0),
    CONSTRAINT premium_plans_label_nonempty CHECK (label <> '')
);

INSERT INTO public.premium_plans
    (months, duration_days, amount_stars, enabled, sort_order, label, version)
VALUES
    (3, 90, 750, true, 10, '3 months', 1),
    (6, 180, 1300, true, 20, '6 months', 1),
    (12, 365, 2400, true, 30, '12 months', 1);

CREATE TABLE public.premium_payment_intents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    form_id bigint NOT NULL,
    idempotency_key text NOT NULL,
    buyer_user_id bigint NOT NULL,
    purchase_kind text NOT NULL,
    recipient_user_id bigint NOT NULL,
    months integer NOT NULL,
    duration_days integer NOT NULL,
    amount_stars bigint NOT NULL,
    currency text DEFAULT 'XTR' NOT NULL,
    plan_version bigint NOT NULL,
    gift_message text DEFAULT '' NOT NULL,
    gift_entities jsonb DEFAULT '[]'::jsonb NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    paid_at timestamp with time zone,
    refunded_at timestamp with time zone,
    stars_transaction_id bigint,
    sender_message_id integer,
    recipient_message_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT premium_payment_intents_pkey PRIMARY KEY (id),
    CONSTRAINT premium_payment_intents_form_unique UNIQUE (form_id),
    CONSTRAINT premium_payment_intents_idempotency_unique UNIQUE (idempotency_key),
    CONSTRAINT premium_payment_intents_idempotency_valid
        CHECK (idempotency_key <> '' AND octet_length(idempotency_key) <= 256),
    CONSTRAINT premium_payment_intents_kind_valid CHECK (purchase_kind IN ('self', 'gift')),
    CONSTRAINT premium_payment_intents_status_valid
        CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'expired', 'refunded')),
    CONSTRAINT premium_payment_intents_currency_xtr CHECK (currency = 'XTR'),
    CONSTRAINT premium_payment_intents_amount_valid
        CHECK (amount_stars > 0 AND amount_stars <= 1000000000000000),
    CONSTRAINT premium_payment_intents_duration_valid
        CHECK (months > 0 AND months <= 120 AND duration_days > 0 AND duration_days <= 36500),
    CONSTRAINT premium_payment_intents_plan_version_positive CHECK (plan_version > 0),
    CONSTRAINT premium_payment_intents_gift_message_valid
        CHECK (char_length(gift_message) <= 128),
    CONSTRAINT premium_payment_intents_gift_entities_valid
        CHECK (CASE WHEN jsonb_typeof(gift_entities) = 'array'
            THEN jsonb_array_length(gift_entities) <= 100 ELSE false END),
    CONSTRAINT premium_payment_intents_form_positive CHECK (form_id > 0),
    CONSTRAINT premium_payment_intents_window_valid CHECK (expires_at > issued_at),
    CONSTRAINT premium_payment_intents_buyer_fkey FOREIGN KEY (buyer_user_id)
        REFERENCES public.users(id) ON DELETE RESTRICT,
    CONSTRAINT premium_payment_intents_recipient_fkey FOREIGN KEY (recipient_user_id)
        REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX premium_payment_intents_buyer_form_idx
    ON public.premium_payment_intents (buyer_user_id, form_id);
CREATE INDEX premium_payment_intents_status_expires_idx
    ON public.premium_payment_intents (status, expires_at);
CREATE INDEX premium_payment_intents_recipient_idx
    ON public.premium_payment_intents (recipient_user_id, id DESC);
CREATE UNIQUE INDEX premium_payment_intents_transaction_unique
    ON public.premium_payment_intents (stars_transaction_id)
    WHERE stars_transaction_id IS NOT NULL;

CREATE TABLE public.premium_entitlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    source text NOT NULL,
    source_user_id bigint DEFAULT 0 NOT NULL,
    payment_intent_id bigint,
    transaction_id bigint,
    months integer NOT NULL,
    duration_days integer NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    status text DEFAULT 'active' NOT NULL,
    command_key text DEFAULT '' NOT NULL,
    revoked_at timestamp with time zone,
    refunded_at timestamp with time zone,
    reason text DEFAULT '' NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT premium_entitlements_pkey PRIMARY KEY (id),
    CONSTRAINT premium_entitlements_source_valid CHECK (source IN ('purchase', 'gift', 'gift_code', 'admin', 'promo')),
    CONSTRAINT premium_entitlements_status_valid CHECK (status IN ('active', 'expired', 'revoked', 'refunded')),
    CONSTRAINT premium_entitlements_duration_valid
        CHECK (months > 0 AND months <= 120 AND duration_days > 0 AND duration_days <= 36500),
    CONSTRAINT premium_entitlements_command_key_valid CHECK (octet_length(command_key) <= 256),
    CONSTRAINT premium_entitlements_window_valid CHECK (expires_at > starts_at),
    CONSTRAINT premium_entitlements_user_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE RESTRICT,
    CONSTRAINT premium_entitlements_payment_fkey FOREIGN KEY (payment_intent_id)
        REFERENCES public.premium_payment_intents(id) ON DELETE RESTRICT,
    CONSTRAINT premium_entitlements_transaction_fkey FOREIGN KEY (transaction_id)
        REFERENCES public.stars_transactions(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX premium_entitlements_payment_unique
    ON public.premium_entitlements (payment_intent_id)
    WHERE payment_intent_id IS NOT NULL;
CREATE UNIQUE INDEX premium_entitlements_transaction_unique
    ON public.premium_entitlements (transaction_id)
    WHERE transaction_id IS NOT NULL;
CREATE UNIQUE INDEX premium_entitlements_admin_command_unique
    ON public.premium_entitlements (source, source_user_id, command_key)
    WHERE command_key <> '';
CREATE INDEX premium_entitlements_user_expires_idx
    ON public.premium_entitlements (user_id, expires_at DESC);
CREATE INDEX premium_entitlements_active_expires_idx
    ON public.premium_entitlements (expires_at, user_id)
    WHERE status = 'active';
CREATE INDEX premium_entitlements_status_idx
    ON public.premium_entitlements (status, id DESC);

CREATE TABLE public.premium_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_user_id bigint DEFAULT 0 NOT NULL,
    target_user_id bigint NOT NULL,
    payment_intent_id bigint,
    entitlement_id bigint,
    action text NOT NULL,
    command_key text DEFAULT '' NOT NULL,
    reason text DEFAULT '' NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT premium_audit_events_pkey PRIMARY KEY (id),
    CONSTRAINT premium_audit_events_action_nonempty CHECK (action <> '')
);

CREATE INDEX premium_audit_events_target_idx
    ON public.premium_audit_events (target_user_id, id DESC);
CREATE INDEX premium_audit_events_payment_idx
    ON public.premium_audit_events (payment_intent_id, id DESC)
    WHERE payment_intent_id IS NOT NULL;
CREATE UNIQUE INDEX premium_audit_events_command_unique
    ON public.premium_audit_events (actor_user_id, action, command_key)
    WHERE command_key <> '';

ALTER TABLE public.stars_transactions
    ADD COLUMN premium_payment_intent_id bigint,
    ADD COLUMN premium_recipient_user_id bigint,
    ADD COLUMN premium_months integer,
    ADD CONSTRAINT stars_transactions_premium_recipient_valid
        CHECK (premium_recipient_user_id IS NULL OR premium_recipient_user_id > 0),
    ADD CONSTRAINT stars_transactions_premium_months_valid
        CHECK (premium_months IS NULL OR (premium_months > 0 AND premium_months <= 120));

CREATE UNIQUE INDEX stars_transactions_premium_payment_unique
    ON public.stars_transactions (premium_payment_intent_id)
    WHERE premium_payment_intent_id IS NOT NULL;

ALTER TABLE public.stars_transactions
    ADD CONSTRAINT stars_transactions_premium_payment_fkey
    FOREIGN KEY (premium_payment_intent_id)
    REFERENCES public.premium_payment_intents(id) ON DELETE RESTRICT;

-- Built-in @premiumbot. The username is reserved during migration rather than
-- lazily on first use, preventing an ordinary account from claiming it.
INSERT INTO public.users (
    id, access_hash, phone, first_name, last_name, username, country_code,
    created_at, updated_at, verified, support, about, last_seen_at,
    default_history_ttl_period, is_bot, bot_info_version, premium_expires_at,
    emoji_status_document_id, emoji_status_until, color_set, color,
    color_background_emoji_id, profile_color_set, profile_color,
    profile_color_background_emoji_id
) VALUES (
    1250000015, 5841763291047652381, '', 'Premium Bot', '', 'premiumbot', '',
    now(), now(), true, false,
    'Покупка Premium для себя или в подарок за Telegram Stars.',
    0, 0, true, 1, NULL, 0, 0, false, 0, 0, false, 0, 0
)
ON CONFLICT (id) DO UPDATE SET
    access_hash = EXCLUDED.access_hash,
    first_name = EXCLUDED.first_name,
    username = EXCLUDED.username,
    verified = EXCLUDED.verified,
    about = EXCLUDED.about,
    is_bot = EXCLUDED.is_bot,
    bot_info_version = GREATEST(public.users.bot_info_version, EXCLUDED.bot_info_version),
    updated_at = now();

INSERT INTO public.bots (
    bot_user_id, owner_user_id, token_secret, description, commands,
    bot_chat_history, bot_nochats, inline_placeholder, created_at, updated_at,
    menu_button_type, menu_button_text, menu_button_url, bot_inline_geo
) VALUES (
    1250000015, 1250000015, '',
    'Покупка Premium для себя или в подарок. Все цены указаны в Telegram Stars.',
    '[
        {"command": "start", "description": "открыть магазин Premium"},
        {"command": "premium", "description": "купить Premium для себя"},
        {"command": "gift", "description": "подарить Premium пользователю"},
        {"command": "status", "description": "проверить статус Premium"},
        {"command": "history", "description": "показать историю покупок"},
        {"command": "terms", "description": "показать условия покупки"},
        {"command": "help", "description": "показать справку"}
    ]'::jsonb,
    false, true, '', now(), now(), 0, '', '', false
)
ON CONFLICT (bot_user_id) DO UPDATE SET
    owner_user_id = EXCLUDED.owner_user_id,
    description = EXCLUDED.description,
    commands = EXCLUDED.commands,
    updated_at = now();

INSERT INTO public.peer_usernames (
    username_lower, username, peer_type, peer_id, active, editable, sort_order, updated_at
)
VALUES ('premiumbot', 'premiumbot', 'user', 1250000015, true, false, 0, now())
ON CONFLICT (username_lower) DO NOTHING;

INSERT INTO public.read_model_versions (model, owner_user_id, peer_type, peer_id, version, updated_at, hash)
VALUES
    ('contact_account', 1250000015, 'user', 1250000015, 1, now(), 2500001500001),
    ('channel_active_memberships', 1250000015, 'user', 1250000015, 1, now(), 2500001500002)
ON CONFLICT (model, owner_user_id, peer_type, peer_id) DO UPDATE SET
    version = GREATEST(public.read_model_versions.version, EXCLUDED.version),
    updated_at = now(),
    hash = EXCLUDED.hash;
